server:
  port: 10110
  tomcat:
    basedir: targer/tomcat
    accesslog:
      enabled: true
  servlet:
    context-path: /     #名字前面一定要加/ 不然启动会报错
spring:
  #mysql
  datasource:
    name: travel
    url: jdbc:mysql://122.51.218.208:3306/travel?useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC
    username: root
    password: Petter123.
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      max-active: 20
      initialSize: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
  application:
    name: travel
    profiles:
      active: dev
  mvc:
    static-path-pattern: /**
    view:
      prefix: classpath:/static/ # 配置静态页面访问前缀

logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    org:
      mybatis: INFO

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mybatis/mapper/**Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.gd.travel.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义SQL注入器
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
