server:
  port: 10110
  tomcat:
    basedir: targer/tomcat
    accesslog:
      enabled: true
  servlet:
    context-path: /     #名字前面一定要加/ 不然启动会报错
spring:
  #mysql
  datasource:
    name: travel
    url: jdbc:mysql://127.0.0.1:3306/travel?useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      max-active: 20
      initialSize: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
  application:
    name: travel
    profiles:
      active: dev
  mvc:
    static-path-pattern: /**
    view:
      prefix: classpath:/static/ # 配置静态页面访问前缀

logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    org:
      mybatis: INFO

